// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lwkcovcbhdotptzphevc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx3a2NvdmNiaGRvdHB0enBoZXZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3OTcyMjYsImV4cCI6MjA3MjM3MzIyNn0.ADspfo1oPN509jwUAQCJoVF_a5xNb8-GSh_TZUtaPx8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});